# Alertmanager Helm chart values configuration
config:
  global:
    resolve_timeout: 5m
  route:
    receiver: 'slack-notifications'
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
  receivers:
    - name: 'slack-notifications'
      slack_configs:
        - send_resolved: true
          channel: '#alerts'
          api_url: 'https://hooks.slack.com/services/your/slack/webhook'
