apiVersion: apps/v1
kind: Deployment
metadata:
  name: socks-shop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socks-shop
  template:
    metadata:
      labels:
        app: socks-shop
    spec:
      containers:
        - name: front-end
          image: weaveworksdemos/front-end:latest
          ports:
            - containerPort: 8079
