name: Deploy Sock Shop Application

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: install kubectl
        run: |
          sudo curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      # install terraform
      - name: install terraform cli
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./deploy/terraform
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: ./deploy/terraform
        run: terraform plan

      # tf apply and deploy to EKS
      - name: Terraform apply
        id: apply
        working-directory: ./deploy/terraform
        run: terraform apply --auto-approve

      - name: AWS EKS with Kubectl
        uses: giovannirossini/aws-eks@v1.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'
          cluster-name: 'socks-shop-cluster'
          command: |
            kubectl apply -f sock-shop-deployment.yaml
